### ISSUE TITLE
Add SSL certificate to template

### ISSUE THREAD

**Issue by minac** [rackspace-orchestration-templates/wordpress-multi#16]
Hi,

As previously discussed over email, can you please add a self signed certificate for the 443 virtual host configured with this template? 
Right now, Apache is listening on port 443 (good), but then has no SSL directives leading to errors when the customer loads the https version of their website (bad).

Thank you.

**Comment by AngieB** [comment]
Hi Brint, any updates regarding this? Or could you direct me to where to include this in the template file? 

Thanks!

**Comment by minac** [comment]
Closing this due to staleness
